import random

# Function to generate incorrect table


def wMulTable(num):
    randomNum = random.randint(0, 9)
    table = [num*n for n in range(1, 11)]
    table[randomNum] = table[randomNum] + random.randint(0, num)
    return table

# Function to check table generated by above function


def checkTable(wtable, num):
    table = [num*n for n in range(1, 11)]
    for i in range(10):
        if table[i] != wtable[i]:
            return f"Table is wrong at index {i} where element value is {wtable[i]} should be {table[i]}."
    return table + "Table is correct"


if __name__ == "__main__":
    num = int(input("Enter the number whose table you want to know: "))
    wtable = wMulTable(num)
    print(wtable)

    ctable = checkTable(wtable, num)
    print(ctable)
